

import { GameConfig, Language } from './types';

export const DEFAULT_CONFIG: GameConfig = {
  pointsPerSet: 25,
  tieBreakPoints: 15,
  hasTieBreak: true,
  maxSets: 5, // Best of 5 (First to 3)
  deuceType: 'standard',
};

export const MIN_LEAD_TO_WIN = 2;

// Calculated based on config, but kept here for reference or utility
export const SETS_TO_WIN_MATCH = (maxSets: number) => Math.ceil(maxSets / 2);

export const THEME = {
  A: {
    // Text color for labels/names
    text: 'text-indigo-900/80 dark:text-indigo-100/90',
    // Score number color (Gradient Text)
    scoreColor: 'text-transparent bg-clip-text bg-gradient-to-br from-indigo-700 to-indigo-900 dark:from-white dark:to-indigo-200',
    // Background gradient for the card (Radial Spotlight)
    bgGradient: 'bg-[radial-gradient(circle_at_center,_var(--tw-gradient-stops))] from-indigo-50 via-slate-50 to-slate-200 dark:from-indigo-950/40 dark:via-[#020617] dark:to-[#020617]',
    // Accent color for indicators
    accent: 'text-indigo-600 dark:text-indigo-400',
    accentBg: 'bg-indigo-600 dark:bg-indigo-500',
    // Glow/Shadow effects
    shadow: 'shadow-indigo-500/20',
    border: 'border-indigo-200 dark:border-indigo-500/20',
    name: 'Home',
    nameKey: 'home'
  },
  B: {
    text: 'text-rose-900/80 dark:text-rose-100/90',
    scoreColor: 'text-transparent bg-clip-text bg-gradient-to-br from-rose-700 to-rose-900 dark:from-white dark:to-rose-200',
    bgGradient: 'bg-[radial-gradient(circle_at_center,_var(--tw-gradient-stops))] from-rose-50 via-slate-50 to-slate-200 dark:from-rose-950/40 dark:via-[#020617] dark:to-[#020617]',
    accent: 'text-rose-600 dark:text-rose-400',
    accentBg: 'bg-rose-600 dark:bg-rose-500',
    shadow: 'shadow-rose-500/20',
    border: 'border-rose-200 dark:border-rose-500/20',
    name: 'Guest',
    nameKey: 'guest'
  }
};

export const TRANSLATIONS = {
  en: {
    home: 'Home',
    guest: 'Guest',
    goal: 'GOAL',
    sets: 'SETS',
    set: 'SET',
    tieBreak: 'TIE BREAK',
    matchOver: 'Match Over',
    wins: 'wins!',
    startNew: 'Start New Match',
    swap: 'SWAP',
    config: 'CONFIG',
    reset: 'RESET MATCH',
    reload: 'RELOAD APP',
    undo: 'UNDO',
    sure: 'Sure?',
    settingsTitle: 'Match Settings',
    matchType: 'Sets to Win Match',
    setsLabel: 'Sets',
    pointsPerSet: 'Points per Set',
    tieBreakPoints: 'Tiebreak Points',
    tieBreakOption: 'Enable Tiebreak (Last Set)',
    tieBreakNote: 'If disabled, last set uses standard points.',
    deuceRule: 'Deuce Rule',
    deuceStd: 'Standard (+2 Advantage)',
    deuceReset: 'Reset @ Deuce (First to 3)',
    deuceInfoTitle: 'Deuce Rule Info:',
    deuceInfoStd: 'Standard: Game continues until 2 point lead (e.g., 26-24).',
    deuceInfoReset: 'Reset: If score ties at set point (e.g., 24-24), scores reset to 0-0. First team to 3 wins.',
    officialRulesTitle: 'Official Volleyball Rules',
    officialRulesText: 'To win a set, a team must reach 25 points with at least a 2-point lead. If the score is 24-24, play continues until a 2-point lead is achieved. The deciding 5th set (Tie-break) is played to 15 points, also requiring a 2-point lead. The match is won by the first team to win 3 sets.',
    save: 'Save & New Match',
    language: 'Language',
    theme: 'Theme',
    firstTo3: 'First to 3',
    appearance: 'Appearance',
    rotate: 'ROTATE',
    matchPoint: 'MATCH POINT',
    setPoint: 'SET POINT',
    timeout: 'TIMEOUT',
    teamManager: 'Team Manager',
    namesList: 'Paste Player Names (one per line)',
    namesPlaceholder: 'John Doe\nJane Smith\n...',
    generateTeams: 'Generate Teams',
    clear: 'Clear',
    queue: 'Queue',
    emptyQueue: 'Empty Queue',
    waiting: 'Waiting',
    fixed: 'Fixed',
    openSlots: 'open slots',
    manageTeams: 'Manage Teams',
    rotationReport: 'Rotation Report',
    rotateAndNext: 'Rotate & Next Match',
    cantRotate: 'No teams in queue',
    stolePlayers: 'stole',
    from: 'from',
    dangerZone: 'Danger Zone',
    factoryReset: 'Factory Reset',
    factoryResetConfirm: 'Delete all data?',
    resetWarning: 'This action cannot be undone.',
    cancel: 'Cancel',
    copy: 'Copy',
    copied: 'Copied',
    winConditionPrefix: 'Win by taking ',
    winConditionSuffix: ' sets first.',
    dragToMove: 'Drag to move',
    tapToLock: 'Tap to lock',
  },
  pt: {
    home: 'Casa',
    guest: 'Visitante',
    goal: 'META',
    sets: 'SETS',
    set: 'SET',
    tieBreak: 'TIE BREAK',
    matchOver: 'Fim de Jogo',
    wins: 'venceu!',
    startNew: 'Nova Partida',
    swap: 'LADOS',
    config: 'AJUSTES',
    reset: 'ZERAR JOGO',
    reload: 'RECARREGAR APP',
    undo: 'VOLTAR',
    sure: 'Certeza?',
    settingsTitle: 'Configurações',
    matchType: 'Sets para Vencer',
    setsLabel: 'Sets',
    pointsPerSet: 'Pontos por Set',
    tieBreakPoints: 'Pontos do Tiebreak',
    tieBreakOption: 'Habilitar Tiebreak (Último Set)',
    tieBreakNote: 'Se desativado, o último set segue a pontuação normal.',
    deuceRule: 'Regra de Desempate',
    deuceStd: 'Padrão (Vantagem de 2)',
    deuceReset: 'Zera no Empate (Vai a 3)',
    deuceInfoTitle: 'Info sobre Desempate:',
    deuceInfoStd: 'Padrão: Jogo segue até abrir 2 pontos de vantagem (ex: 26-24).',
    deuceInfoReset: 'Reset: Se empatar no set point (ex: 24-24), o placar zera (0-0). Ganha quem fizer 3 pontos primeiro.',
    officialRulesTitle: 'Regras Oficiais (Resumo)',
    officialRulesText: 'Para vencer um set, a equipe deve alcançar 25 pontos com minímo de 2 pontos de vantagem (ex: 26-24). O Tie-break (5º set) vai a 15 pontos, também com vantagem de 2. Vence a partida quem ganhar o número de sets estipulado (geralmente 3). Sistema "Rally Point": Ponto direto em toda jogada.',
    save: 'Salvar e Reiniciar',
    language: 'Idioma',
    theme: 'Tema',
    firstTo3: 'Quem fizer 3',
    appearance: 'Aparência',
    rotate: 'GIRAR',
    matchPoint: 'MATCH POINT',
    setPoint: 'SET POINT',
    timeout: 'TEMPO',
    teamManager: 'Gerenciar Times',
    namesList: 'Cole os Nomes (um por linha)',
    namesPlaceholder: 'João Silva\nMaria Souza\n...',
    generateTeams: 'Gerar Times',
    clear: 'Limpar',
    queue: 'Fila de Espera',
    emptyQueue: 'Fila Vazia',
    waiting: 'Aguardando',
    fixed: 'Fixo',
    openSlots: 'vagas abertas',
    manageTeams: 'Gerir Times',
    rotationReport: 'Relatório de Rotação',
    rotateAndNext: 'Rodar & Próximo Jogo',
    cantRotate: 'Sem fila de espera',
    stolePlayers: 'roubou',
    from: 'de',
    dangerZone: 'Zona de Perigo',
    factoryReset: 'Reset Geral',
    factoryResetConfirm: 'Apagar tudo?',
    resetWarning: 'Esta ação não pode ser desfeita.',
    cancel: 'Cancelar',
    copy: 'Copiar',
    copied: 'Copiado',
    winConditionPrefix: 'Ganha quem vencer ',
    winConditionSuffix: ' sets primeiro.',
    dragToMove: 'Arraste p/ mover',
    tapToLock: 'Toque p/ fixar',
  }
};

export const t = (lang: Language, key: keyof typeof TRANSLATIONS['en']) => {
  return TRANSLATIONS[lang][key] || key;
};